### ISSUE TITLE
Will slides be avalaible?

### ISSUE THREAD

**Issue by adrianjarc** [rodrigo-pena/amld2019-graph-workshop#2]
Hello, 

I was wondering if slides will be avalaible and when?
If i click the link in Readme it doesn't work.

Thank you.

**Comment by rodrigo-pena** [comment]
Hi, the link is not active yet. But check again in a couple of days and it should point you to the pdfs of the slides.

**Comment by mdeff** [comment]
The slides are now available at <https://doi.org/10.5281/zenodo.2551081> (README link fixed in 63e0d39346f261c1f6503e931d05822b8fed54ba).
